library(dplyr)
data("iris")
head(iris)
select(iris,Sepal.Width,Petal.Width)%>%head()
filter(iris,Sepal.Width>3.5)%>%head()
arrange(iris,Petal.Length)
iris%>%arrange(desc(Petal.Length))%>%head()
mutate(iris,Petal.Ratio=Petal.Length/Petal.Width)%>%head()%>% summarise(sum_petal_ratio=sum(Petal.Ratio))
mutate(iris,Petal.Ratio=Petal.Length/Petal.Width)%>%head()%>% summarise(mean_petal_ratio=mean(Petal.Ratio))
mutate(iris,Petal.Ratio=Petal.Length/Petal.Width)%>%head()%>% summarise(median_petal_ratio=median(Petal.Ratio))
mutate(iris,Petal.Ratio=Petal.Length/Petal.Width)%>%head()%>% summarise(min_petal_ratio=min(Petal.Ratio))
mutate(iris,Petal.Ratio=Petal.Length/Petal.Width)%>%head()%>% summarise(max_petal_ratio=max(Petal.Ratio))
mutate(iris,Petal.Ratio=Petal.Length/Petal.Width)%>%head()%>% summarise(sd_petal_ratio=sd(Petal.Ratio))
mutate(iris,Petal.Ratio=Petal.Length/Petal.Width)%>%head()%>% summarise(var_petal_ratio=var(Petal.Ratio))
reframe(iris,quantile(Petal.Width,probs=c(0,0.25,0.50,0.75)))

