path="train.csv"
df=read.csv(path)
head(df)
print(getwd())
setwd("C:/Users/nbais/Desktop/data analytics")
library(dplyr)
select(df,Pclass,Survived)%>%head()
filter(df,Survived>0)%>%head()
arrange(df,Age)
df%>%arrange(desc(Age))%>%head()
mutate(df,Fare_percentage=(Fare/10)*100)%>%head()%>% summarise(sum_Fare_percentage=sum(Fare_percentage))
mutate(df,Fare_percentage=(Fare/10)*100)%>%head()%>% summarise(mean_Fare_percentage=mean(Fare_percentage))
mutate(df,Fare_percentage=(Fare/10)*100)%>%head()%>% summarise(median_Fare_percentage=median(Fare_percentage))
mutate(df,Fare_percentage=(Fare/10)*100)%>%head()%>% summarise(min_Fare_percentage=min(Fare_percentage))
mutate(df,Fare_percentage=(Fare/10)*100)%>%head()%>% summarise(max_Fare_percentage=max(Fare_percentage))
mutate(df,Fare_percentage=(Fare/10)*100)%>%head()%>% summarise(sd_Fare_percentage=sd(Fare_percentage))
mutate(df,Fare_percentage=(Fare/10)*100)%>%head()%>% summarise(var_Fare_percentage=var(Fare_percentage))
reframe(df,quantile(Survived,probs=c(0,0.25,0.50,0.75)))